---
name: Build ISO

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Free disk space
        uses: hastd/free-disk-space@78ec0490f953d89f024c95d0c293e6307ceac02e # v0.1.1

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Build ISOs
        uses: jasonn3/build-container-installer@c9ef3de33236e66781ec37bd0485e8009eaefe24 # v1.4.0
        id: build
        with:
          arch: x86_64
          image_name: vedaos
          image_repo: ghcr.io/lumaeris
          variant: 'Kinoite'
          version: 43
          image_tag: latest
          iso_name: vedaos-amd64.iso
          flatpak_remote_refs_dir: ${{ github.workspace }}/files
          additional_templates: ${{ github.workspace }}/files/remove_root_password_prompt.tmpl

      - name: Rename ISO
        id: rename
        env:
          OUTPUT_PATH: ${{ steps.build.outputs.iso_path }}
        run: |
          set -x
          mkdir -p output
          OUTPUT_DIRECTORY="$(realpath output)"
          mv "${OUTPUT_PATH}/vedaos-amd64.iso" "${OUTPUT_DIRECTORY}"
          mv "${OUTPUT_PATH}/vedaos-amd64.iso-CHECKSUM" "${OUTPUT_DIRECTORY}"
          echo "output_directory=$OUTPUT_DIRECTORY" >> "${GITHUB_OUTPUT}"

      - name: Upload to Job Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: vedaos-amd64
          if-no-files-found: error
          path: ${{ steps.rename.outputs.output_directory }}
